/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.indikaudaya.oodp2.model;

import com.indikaudaya.oodp2.service.ImageSetter;
import com.indikaudaya.oodp2.service.MainPanel;
import com.indikaudaya.oodp2.service.PanelSetter;
import com.indikaudaya.oodp2.view.CustomerHome;
import javax.swing.JLabel;

/**
 *
 * @author indika
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     *
     * @param itemDetail
     */
    ItemDetail itemDetail;
    PanelSetter panelSetter;
    MainPanel mainPanel;

    public ItemPanel(ItemDetail itemDetail, CustomerHome customerHome) {
        initComponents();
        this.itemDetail = itemDetail;
        this.panelSetter = customerHome;
        this.mainPanel = customerHome;
        setDetail();
        lockButton(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addItemCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imagePath = new javax.swing.JLabel();
        itemName = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(220, 220));
        setMinimumSize(new java.awt.Dimension(220, 220));
        setPreferredSize(new java.awt.Dimension(220, 220));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(220, 220));
        jPanel1.setMinimumSize(new java.awt.Dimension(220, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addItemCount.setBackground(new java.awt.Color(255, 0, 0));
        addItemCount.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        addItemCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addItemCount.setText("00");
        jPanel1.add(addItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/resource/bell.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(14, 17));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 30));

        imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/resource/defaultImage.png"))); // NOI18N
        imagePath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        imagePath.setMaximumSize(new java.awt.Dimension(200, 113));
        imagePath.setMinimumSize(new java.awt.Dimension(200, 113));
        imagePath.setPreferredSize(new java.awt.Dimension(200, 113));
        jPanel1.add(imagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 130));

        itemName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemName.setText("Item Name");
        jPanel1.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 30));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setText("Price");
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/resource/minus.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/resource/add.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        addItemCount.setText(String.valueOf(Integer.parseInt(addItemCount.getText()) + 1));
        createListPanelInstance("+");;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        itemMinus();
        createListPanelInstance("-");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel addItemCount;
    public javax.swing.JLabel imagePath;
    public javax.swing.JLabel itemName;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables

    private void setImage(String path) {
        ImageSetter.setImageToLabel(imagePath, 200, 113, path);
    }

    private void setDetail() {
        setImage(itemDetail.getPath());
        price.setText("Rs. ".concat(String.valueOf(itemDetail.getPrice())));
        itemName.setText(itemDetail.getItemName());
    }

    private void lockButton(boolean par) {
        jButton2.setEnabled(par);
    }

//    private void itemMinus() {
//        int c = Integer.parseInt(addItemCount.getText());
//
////        if (c == 0) {
////            jButton2.setEnabled(false);
////            addItemCount.setText("00");
////        }
//        panelSetter.panelSet(itemDetail, "-");
////        createListPanelInstance("-");
//    }

    private void createListPanelInstance(String sign) {
        String key = itemName.getText().concat(" ").concat(String.valueOf(price.getText()));
        ItemPanel panel = CustomerHome.MAIN_PANEL_POOL.get(key);
        if (panel == null) {
            addItemCount.setText("1");
            lockFeild();
            panel = this;
            CustomerHome.MAIN_PANEL_POOL.put(key, panel);
        } else {
            JLabel itemCount = panel.addItemCount;
            if (sign.equals("+")) {
                itemCount.setText(String.valueOf(Integer.parseInt(addItemCount.getText()) + 1));
                lockFeild();
            } else {
//                itemCount.setText(String.valueOf(Integer.parseInt(addItemCount.getText()) - 1));
                mainPanel.getMainPanelByCustomer(key);
               panelSetter.panelSet(itemDetail, "-");
            }
        }
        addItemCount.setText(panel.addItemCount.getText());
    }

    private void lockFeild() {
        jButton2.setEnabled(!addItemCount.getText().equalsIgnoreCase("00") && !addItemCount.getText().equalsIgnoreCase("0"));
        panelSetter.panelSet(itemDetail, "+");
        lockButton(true);
    }

}
