/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.indikaudaya.oodp2.model;

import com.indikaudaya.oodp2.service.MainPanel;
import com.indikaudaya.oodp2.service.PurchasePanelRemove;

/**
 *
 * @author indika
 */
public class ItemListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     *
     */
    ItemDetail itemDetail;
    PurchasePanelRemove purchasePanelRemove;
    MainPanel mainPanel;

    public ItemListPanel(ItemDetail itemDetail, PurchasePanelRemove purchasePanelRemove) {
        initComponents();
        this.itemDetail = itemDetail;
        this.purchasePanelRemove = purchasePanelRemove;
        this.mainPanel = (MainPanel) purchasePanelRemove;
        setDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemCount = new javax.swing.JLabel();
        itemName = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(220, 104));
        setMinimumSize(new java.awt.Dimension(220, 104));
        setPreferredSize(new java.awt.Dimension(220, 104));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(220, 220));
        jPanel1.setMinimumSize(new java.awt.Dimension(220, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemCount.setBackground(new java.awt.Color(255, 0, 0));
        itemCount.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        itemCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCount.setText("00");
        jPanel1.add(itemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 20));

        itemName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemName.setText("Item Name");
        jPanel1.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setText("Price");
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/resource/minus.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        itemCount.setText(String.valueOf(Integer.parseInt(itemCount.getText()) - 1));
        purchasePanelRemove.amountMinus();
        purchasePanelRemove.removePanel(itemDetail);
        String key = itemDetail.getItemName().concat(" ").concat("Rs. ".concat(String.valueOf(itemDetail.getPrice())));
        mainPanel.getMainPanelByCustomer(key);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel itemCount;
    public javax.swing.JLabel itemName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables

    private void setDetail() {
        price.setText("Rs. ".concat(String.valueOf(itemDetail.getPrice())));
        itemName.setText(itemDetail.getItemName());
        itemCount.setText("1");
    }

}
