/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.indikaudaya.oodp2.view;

import com.indikaudaya.oodp2.controller.AmountCalculatorController;
import com.indikaudaya.oodp2.controller.LoadFoodItemController;
import com.indikaudaya.oodp2.model.Database;
import com.indikaudaya.oodp2.model.ItemDetail;
import com.indikaudaya.oodp2.model.ItemListPanel;
import com.indikaudaya.oodp2.model.ItemPanel;
import com.indikaudaya.oodp2.model.Orders;
import com.indikaudaya.oodp2.service.AmountSetter;
import com.indikaudaya.oodp2.service.MainPanel;
import com.indikaudaya.oodp2.service.PanelSetter;
import com.indikaudaya.oodp2.service.PurchasePanelRemove;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author indika
 */
public class CustomerHome extends javax.swing.JFrame implements PanelSetter, PurchasePanelRemove, AmountSetter, MainPanel {

    /**
     * Creates new form CustomerHome
     */
    private static final Map<String, ItemListPanel> FOOD_ITEM_POOL = new HashMap<>();
    public static final Map<String, ItemPanel> MAIN_PANEL_POOL = new HashMap<>();

    public CustomerHome() {
        initComponents();
        setItemMeals();
        MAIN_PANEL_POOL.clear();
        FOOD_ITEM_POOL.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 50, 40));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 223, 300, 100));

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 310, 100));

        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 310, 100));

        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 310, 110));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/resource/checkout.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 710, 150, 50));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 480, 590));

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, -1, -1));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jScrollPane2.setViewportView(jPanel3);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 260, 450));

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 675, 90, 20));

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel2.setText("Category Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indikaudaya/oodp2/view/customerHome.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new LoadFoodItemController(this, new Database()).updateShorteatsView();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoadFoodItemController(this, new Database()).updateMealsView();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new LoadFoodItemController(this, new Database()).updateDessertsView();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new LoadFoodItemController(this, new Database()).updateBeverageView();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        checkout();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void setFoodItem(Map<String, ItemDetail> foodItem, String viewName) {
        jLabel2.setText(viewName);
        jPanel2.removeAll();
        jPanel2.invalidate();
        jPanel2.repaint();

        foodItem.forEach((t, u) -> {
            ItemPanel itemPanel = new ItemPanel(u, this);
            jPanel2.add(itemPanel);

        });
    }

    private void setItemMeals() {
        new LoadFoodItemController(this, new Database()).updateMealsView();
    }

    private void addPanel(ItemListPanel itemListPanel) {
        jPanel3.add(itemListPanel);
        jPanel3.invalidate();
        jPanel3.repaint();
    }

    private void createListPanelInstance(ItemDetail detail, String sign) {
        String key = detail.getItemName().concat(" ").concat(String.valueOf(detail.getPrice()));
        ItemListPanel panel = FOOD_ITEM_POOL.get(key);
        if (panel == null) {
            panel = new ItemListPanel(detail, this);
            FOOD_ITEM_POOL.put(key, panel);
        } else {
            JLabel itemCount = panel.itemCount;
            if (sign.equals("+")) {
                itemCount.setText(String.valueOf(Integer.parseInt(itemCount.getText()) + 1));
            } else {
                itemCount.setText(String.valueOf(Integer.parseInt(itemCount.getText()) - 1));
            }
        }
        expressionGenerator();
        addPanel(panel);
        panelRemove1(panel, detail);
    }

    @Override
    public void panelSet(ItemDetail itemDetail, String sign) {
        createListPanelInstance(itemDetail, sign);
    }

    private void panelRemove1(ItemListPanel panel, ItemDetail detail) {
        if (Integer.parseInt(panel.itemCount.getText()) == 0) {
            String key = detail.getItemName().concat(" ").concat(String.valueOf(detail.getPrice()));
            FOOD_ITEM_POOL.remove(key);
            jPanel3.remove(panel);
            jPanel3.invalidate();
            jPanel3.repaint();
        }
    }

    @Override
    public void removePanel(ItemDetail detail) {
        String key = detail.getItemName().concat(" ").concat(String.valueOf(detail.getPrice()));
        ItemListPanel panel = FOOD_ITEM_POOL.get(key);
        panelRemove1(panel, detail);
    }

    public void expressionGenerator() {
        final double[] amount = new double[1];
        List expression = new ArrayList();

        FOOD_ITEM_POOL.forEach((t, u) -> {
            double amt = Double.parseDouble(u.price.getText().substring(3, u.price.getText().length())) * Integer.parseInt(u.itemCount.getText());
            amount[0] += amt;
            expression.add(amt);
            expression.add("+");
        });
        expression.remove(expression.size() - 1);
        new AmountCalculatorController(this).calculateAmount(expression);
    }

    @Override
    public void amountMinus() {
        expressionGenerator();
    }

    @Override
    public void setValues(double amount) {
        jLabel4.setText("Rs. " + amount);
    }

    private void checkout() {
        if (!FOOD_ITEM_POOL.isEmpty()) {
            expressionGenerator();
            Orders order = new Orders.Builder()
                    .setAmount(Double.parseDouble(jLabel4.getText().substring(3, jLabel4.getText().length())))
                    .setCustomerName("non")
                    .setOrderItem(FOOD_ITEM_POOL)
                    .setOrderNumber(new AtomicInteger(100).incrementAndGet())
                    .build();
            new Checkout(this, true,order,this).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please add item first!.", "Checkout", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void getMainPanelByCustomer(String key) {
        ItemPanel get = MAIN_PANEL_POOL.get(key);
        get.addItemCount.setText(Integer.parseInt(get.addItemCount.getText()) - 1 + "");
        if (get.addItemCount.getText().equals("0")) {
            get.jButton2.setEnabled(false);
        }
    }

}
